//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigByteTechnologies.Windows.AHKSnipit.HotList.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BigByteTechnologies.Windows.AHKSnipit.HotList.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program is distributed under the terms of the GNU General Public License v3 or later..
        /// </summary>
        internal static string AboutDistMsg {
            get {
                return ResourceManager.GetString("AboutDistMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt; Select All &gt;&gt;.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap binary16 {
            get {
                object obj = ResourceManager.GetObject("binary16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap copy_doc16 {
            get {
                object obj = ResourceManager.GetObject("copy_doc16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap copy_doc32 {
            get {
                object obj = ResourceManager.GetObject("copy_doc32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Confirm.
        /// </summary>
        internal static string DeleteConfirmTitle {
            get {
                return ResourceManager.GetString("DeleteConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this item?.
        /// </summary>
        internal static string DeleteGeneralQuestion {
            get {
                return ResourceManager.GetString("DeleteGeneralQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete fail for the follonw reason:{0}{1}.
        /// </summary>
        internal static string DeleteMsgFailReasonText {
            get {
                return ResourceManager.GetString("DeleteMsgFailReasonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Failed.
        /// </summary>
        internal static string DeleteMsgFailTitle {
            get {
                return ResourceManager.GetString("DeleteMsgFailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete was successful..
        /// </summary>
        internal static string DeleteMsgSuccessText {
            get {
                return ResourceManager.GetString("DeleteMsgSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string DeleteMsgSuccessTitle {
            get {
                return ResourceManager.GetString("DeleteMsgSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the Plugin &apos;{1}&apos;?{0}This action can not be undone!.
        /// </summary>
        internal static string DeletePluginConfirmText {
            get {
                return ResourceManager.GetString("DeletePluginConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the Profile &apos;{1}&apos;?{0}This will delete all the plugins for this Profile as well.{0}This action can not be undone!.
        /// </summary>
        internal static string DeleteProfileConfirmText {
            get {
                return ResourceManager.GetString("DeleteProfileConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        internal static string DisableText {
            get {
                return ResourceManager.GetString("DisableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        internal static string EnableText {
            get {
                return ResourceManager.GetString("EnableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate {0}.
        /// </summary>
        internal static string ErrorDuplicateKey {
            get {
                return ResourceManager.GetString("ErrorDuplicateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is No Default Profile. Unable to locate or set up a profile. Contact your administrator..
        /// </summary>
        internal static string ErrorNoProfileText {
            get {
                return ResourceManager.GetString("ErrorNoProfileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Profile.
        /// </summary>
        internal static string ErrorNoProfileTitle {
            get {
                return ResourceManager.GetString("ErrorNoProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set the current profile. Unknown File name!.
        /// </summary>
        internal static string ErrorSettingIniProfileNoFileText {
            get {
                return ResourceManager.GetString("ErrorSettingIniProfileNoFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing File Name.
        /// </summary>
        internal static string ErrorSettingIniProfileNoFileTitle {
            get {
                return ResourceManager.GetString("ErrorSettingIniProfileNoFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorTitleError {
            get {
                return ResourceManager.GetString("ErrorTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exit_16 {
            get {
                object obj = ResourceManager.GetObject("exit_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap export {
            get {
                object obj = ResourceManager.GetObject("export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File as exported successfully.
        /// </summary>
        internal static string FileExportedMessage {
            get {
                return ResourceManager.GetString("FileExportedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Export.
        /// </summary>
        internal static string FileExportTitle {
            get {
                return ResourceManager.GetString("FileExportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Spy.
        /// </summary>
        internal static string FileFindWindwSpyTitle {
            get {
                return ResourceManager.GetString("FileFindWindwSpyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoHotkey Snippit.chm.
        /// </summary>
        internal static string FileHelpName {
            get {
                return ResourceManager.GetString("FileHelpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flag_green_16 {
            get {
                object obj = ResourceManager.GetObject("flag_green_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flag_red_16 {
            get {
                object obj = ResourceManager.GetObject("flag_red_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FolderCopy16 {
            get {
                object obj = ResourceManager.GetObject("FolderCopy16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FolderMove16 {
            get {
                object obj = ResourceManager.GetObject("FolderMove16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HotList.
        /// </summary>
        internal static string FormHotListTitle {
            get {
                return ResourceManager.GetString("FormHotListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap green_light16 {
            get {
                object obj = ResourceManager.GetObject("green_light16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey.
        /// </summary>
        internal static string HotKey {
            get {
                return ResourceManager.GetString("HotKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HotString.
        /// </summary>
        internal static string HotString {
            get {
                return ResourceManager.GetString("HotString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap import {
            get {
                object obj = ResourceManager.GetObject("import", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Complete.
        /// </summary>
        internal static string ImportCompleteText {
            get {
                return ResourceManager.GetString("ImportCompleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Complete.
        /// </summary>
        internal static string ImportCompleteTitle {
            get {
                return ResourceManager.GetString("ImportCompleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is not valid for import.
        /// </summary>
        internal static string ImportInvalidFileText {
            get {
                return ResourceManager.GetString("ImportInvalidFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid File.
        /// </summary>
        internal static string ImportInvalidFileTitle {
            get {
                return ResourceManager.GetString("ImportInvalidFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The import Minimum Version Requirement has not been met. You may need to upgrade this Application to install this plugin(s)..
        /// </summary>
        internal static string ImportMinVersionErrorText {
            get {
                return ResourceManager.GetString("ImportMinVersionErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Error.
        /// </summary>
        internal static string ImportMinVersionErrorTitle {
            get {
                return ResourceManager.GetString("ImportMinVersionErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not Profile Named {0}. Plugins must have a matching Profile to be imported..
        /// </summary>
        internal static string ImportNoMatchingProfileText {
            get {
                return ResourceManager.GetString("ImportNoMatchingProfileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Matching Profile.
        /// </summary>
        internal static string ImportNoMatchingProfileTitle {
            get {
                return ResourceManager.GetString("ImportNoMatchingProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap matrix_logo_500 {
            get {
                object obj = ResourceManager.GetObject("matrix_logo_500", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} plugin has been copied.
        /// </summary>
        internal static string PluginCopySuccessText {
            get {
                return ResourceManager.GetString("PluginCopySuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin Copied.
        /// </summary>
        internal static string PluginCopySuccessTitle {
            get {
                return ResourceManager.GetString("PluginCopySuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to disable Plugin.
        /// </summary>
        internal static string PluginDisableTooltip {
            get {
                return ResourceManager.GetString("PluginDisableTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to enable Plugin.
        /// </summary>
        internal static string PluginEnableTooltip {
            get {
                return ResourceManager.GetString("PluginEnableTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} plug has been moved.
        /// </summary>
        internal static string PluginMoveSuccessText {
            get {
                return ResourceManager.GetString("PluginMoveSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin Moved.
        /// </summary>
        internal static string PluginMoveSuccessTitle {
            get {
                return ResourceManager.GetString("PluginMoveSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile {0} alread exist..
        /// </summary>
        internal static string ProfileExistText {
            get {
                return ResourceManager.GetString("ProfileExistText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Exist.
        /// </summary>
        internal static string ProfileExistTitle {
            get {
                return ResourceManager.GetString("ProfileExistTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ProfileWindowName {
            get {
                return ResourceManager.GetString("ProfileWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        internal static string ProfileWindowValue {
            get {
                return ResourceManager.GetString("ProfileWindowValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap red_light16 {
            get {
                object obj = ResourceManager.GetObject("red_light16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to replace {0} contents?.
        /// </summary>
        internal static string ReplaceValue {
            get {
                return ResourceManager.GetString("ReplaceValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace {0}.
        /// </summary>
        internal static string ReplaceValueTitle {
            get {
                return ResourceManager.GetString("ReplaceValueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save_16 {
            get {
                object obj = ResourceManager.GetObject("save_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap swap16 {
            get {
                object obj = ResourceManager.GetObject("swap16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap text16 {
            get {
                object obj = ResourceManager.GetObject("text16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The install file has successfully validated..
        /// </summary>
        internal static string ValidateInstallSuccess {
            get {
                return ResourceManager.GetString("ValidateInstallSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin file has successfully validated..
        /// </summary>
        internal static string ValidatePluginSuccess {
            get {
                return ResourceManager.GetString("ValidatePluginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate Install.
        /// </summary>
        internal static string ValidationDialogInstallTitle {
            get {
                return ResourceManager.GetString("ValidationDialogInstallTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate Plugin.
        /// </summary>
        internal static string ValidationDialogPluginTitle {
            get {
                return ResourceManager.GetString("ValidationDialogPluginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile File.
        /// </summary>
        internal static string ValidationDialogProfileOpen {
            get {
                return ResourceManager.GetString("ValidationDialogProfileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate Profile.
        /// </summary>
        internal static string ValidationDialogProfileTitle {
            get {
                return ResourceManager.GetString("ValidationDialogProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicates are not allowed for {0}.
        /// </summary>
        internal static string ValidationDublicateNotAllowed {
            get {
                return ResourceManager.GetString("ValidationDublicateNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} contains too many characeters; Maximum length is {1}.
        /// </summary>
        internal static string ValidationFieldToLong {
            get {
                return ResourceManager.GetString("ValidationFieldToLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid format.
        /// </summary>
        internal static string ValidationFormat {
            get {
                return ResourceManager.GetString("ValidationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Key combination for {0}.
        /// </summary>
        internal static string ValidationInvalidKeyCombination {
            get {
                return ResourceManager.GetString("ValidationInvalidKeyCombination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min length for {0} is {1} characters.
        /// </summary>
        internal static string ValidationMinLength {
            get {
                return ResourceManager.GetString("ValidationMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must only contain number letters and underscore characters.
        /// </summary>
        internal static string ValidationNumberLettersUnserscore {
            get {
                return ResourceManager.GetString("ValidationNumberLettersUnserscore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile File.
        /// </summary>
        internal static string ValidationProfileOpenText {
            get {
                return ResourceManager.GetString("ValidationProfileOpenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is Required.
        /// </summary>
        internal static string ValidationRequired {
            get {
                return ResourceManager.GetString("ValidationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install File.
        /// </summary>
        internal static string ValidatoinDialogInstalOpenText {
            get {
                return ResourceManager.GetString("ValidatoinDialogInstalOpenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin File.
        /// </summary>
        internal static string ValidatoinDialogPluginOpenText {
            get {
                return ResourceManager.GetString("ValidatoinDialogPluginOpenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has to be set.
        /// </summary>
        internal static string ValueHasToBeSet {
            get {
                return ResourceManager.GetString("ValueHasToBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap windowspy {
            get {
                object obj = ResourceManager.GetObject("windowspy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
