//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

namespace BigByteTechnologies.Windows.Library.AHKSnipit.AHKSnipitLib.Maps
{

    // 
    // This source code was auto-generated by xsd, Version=4.6.1055.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class AhkKeyMap
    {

        private AhkKeyMapAhkMapValue[] ahkMapValueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AhkMapValue")]
        public AhkKeyMapAhkMapValue[] AhkMapValue
        {
            get
            {
                return this.ahkMapValueField;
            }
            set
            {
                this.ahkMapValueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AhkKeyMapAhkMapValue
    {

        private string keyField;

        private string autoHotKeyValueField;

        private string displayValueField;

        private int sortField;

        public AhkKeyMapAhkMapValue()
        {
            this.sortField = 0;
        }

        /// <remarks/>
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }

        /// <remarks/>
        public string AutoHotKeyValue
        {
            get
            {
                return this.autoHotKeyValueField;
            }
            set
            {
                this.autoHotKeyValueField = value;
            }
        }

        /// <remarks/>
        public string DisplayValue
        {
            get
            {
                return this.displayValueField;
            }
            set
            {
                this.displayValueField = value;
            }
        }

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int Sort
        {
            get
            {
                return this.sortField;
            }
            set
            {
                this.sortField = value;
            }
        }
    }

}
