//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

namespace BigByteTechnologies.Windows.Library.AHKSnipit.AHKSnipitLib.Plugin
{

    // 
    // This source code was auto-generated by xsd, Version=4.6.1055.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class profile
    {

        private profileCodeLanguage codeLanguageField;

        private profileWindow[] windowsField;

        private EndCharsEnum[] profileEndCharsField;

        private string versionField;

        private string minVersionField;

        private string nameField;

        private bool globalProfileField;

        private decimal schemaVersionField;

        public profile()
        {
            this.globalProfileField = false;
        }

        /// <remarks/>
        public profileCodeLanguage codeLanguage
        {
            get
            {
                return this.codeLanguageField;
            }
            set
            {
                this.codeLanguageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("window", IsNullable = false)]
        public profileWindow[] windows
        {
            get
            {
                return this.windowsField;
            }
            set
            {
                this.windowsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("profileEndChar", IsNullable = false)]
        public EndCharsEnum[] profileEndChars
        {
            get
            {
                return this.profileEndCharsField;
            }
            set
            {
                this.profileEndCharsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string minVersion
        {
            get
            {
                return this.minVersionField;
            }
            set
            {
                this.minVersionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool globalProfile
        {
            get
            {
                return this.globalProfileField;
            }
            set
            {
                this.globalProfileField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal schemaVersion
        {
            get
            {
                return this.schemaVersionField;
            }
            set
            {
                this.schemaVersionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class profileCodeLanguage
    {

        private string codeNameField;

        private string descriptionField;

        private profileCodeLanguagePaths pathsField;

        /// <remarks/>
        public string codeName
        {
            get
            {
                return this.codeNameField;
            }
            set
            {
                this.codeNameField = value;
            }
        }

        /// <remarks/>
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public profileCodeLanguagePaths paths
        {
            get
            {
                return this.pathsField;
            }
            set
            {
                this.pathsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class profileCodeLanguagePaths
    {

        private string mainDataField;

        private string pluginField;

        private string snipsField;

        private string dataItemsPathField;

        /// <remarks/>
        public string mainData
        {
            get
            {
                return this.mainDataField;
            }
            set
            {
                this.mainDataField = value;
            }
        }

        /// <remarks/>
        public string plugin
        {
            get
            {
                return this.pluginField;
            }
            set
            {
                this.pluginField = value;
            }
        }

        /// <remarks/>
        public string snips
        {
            get
            {
                return this.snipsField;
            }
            set
            {
                this.snipsField = value;
            }
        }

        /// <remarks/>
        public string dataItemsPath
        {
            get
            {
                return this.dataItemsPathField;
            }
            set
            {
                this.dataItemsPathField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class profileWindow
    {

        private string nameField;

        private string valueField;

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    public enum EndCharsEnum
    {

        /// <remarks/>
        Zero,

        /// <remarks/>
        One,

        /// <remarks/>
        Two,

        /// <remarks/>
        Three,

        /// <remarks/>
        Four,

        /// <remarks/>
        Five,

        /// <remarks/>
        Six,

        /// <remarks/>
        Seven,

        /// <remarks/>
        Eight,

        /// <remarks/>
        Nine,

        /// <remarks/>
        Upper_A,

        /// <remarks/>
        Upper_B,

        /// <remarks/>
        Upper_C,

        /// <remarks/>
        Upper_D,

        /// <remarks/>
        Upper_E,

        /// <remarks/>
        Upper_F,

        /// <remarks/>
        Upper_G,

        /// <remarks/>
        Upper_H,

        /// <remarks/>
        Upper_I,

        /// <remarks/>
        Upper_J,

        /// <remarks/>
        Upper_K,

        /// <remarks/>
        Upper_L,

        /// <remarks/>
        Upper_M,

        /// <remarks/>
        Upper_N,

        /// <remarks/>
        Upper_O,

        /// <remarks/>
        Upper_P,

        /// <remarks/>
        Upper_Q,

        /// <remarks/>
        Upper_R,

        /// <remarks/>
        Upper_S,

        /// <remarks/>
        Upper_T,

        /// <remarks/>
        Upper_U,

        /// <remarks/>
        Upper_V,

        /// <remarks/>
        Upper_W,

        /// <remarks/>
        Upper_X,

        /// <remarks/>
        Upper_Y,

        /// <remarks/>
        Upper_Z,

        /// <remarks/>
        Lower_A,

        /// <remarks/>
        Lower_B,

        /// <remarks/>
        Lower_C,

        /// <remarks/>
        Lower_D,

        /// <remarks/>
        Lower_E,

        /// <remarks/>
        Lower_F,

        /// <remarks/>
        Lower_G,

        /// <remarks/>
        Lower_H,

        /// <remarks/>
        Lower_I,

        /// <remarks/>
        Lower_J,

        /// <remarks/>
        Lower_K,

        /// <remarks/>
        Lower_L,

        /// <remarks/>
        Lower_M,

        /// <remarks/>
        Lower_N,

        /// <remarks/>
        Lower_O,

        /// <remarks/>
        Lower_P,

        /// <remarks/>
        Lower_Q,

        /// <remarks/>
        Lower_R,

        /// <remarks/>
        Lower_S,

        /// <remarks/>
        Lower_T,

        /// <remarks/>
        Lower_U,

        /// <remarks/>
        Lower_V,

        /// <remarks/>
        Lower_W,

        /// <remarks/>
        Lower_X,

        /// <remarks/>
        Lower_Y,

        /// <remarks/>
        Lower_Z,

        /// <remarks/>
        Space,

        /// <remarks/>
        Tab,

        /// <remarks/>
        Enter,

        /// <remarks/>
        And,

        /// <remarks/>
        SingleQuote,

        /// <remarks/>
        DoubleQuote,

        /// <remarks/>
        Asterisk,

        /// <remarks/>
        AT,

        /// <remarks/>
        BackQuote,

        /// <remarks/>
        BackSlash,

        /// <remarks/>
        ForwardShash,

        /// <remarks/>
        CurlyBraceOpen,

        /// <remarks/>
        CurlyBraceClose,

        /// <remarks/>
        SquareBracketOpen,

        /// <remarks/>
        SqureBracketClose,

        /// <remarks/>
        OpenParenthesis,

        /// <remarks/>
        CloseParenthesis,

        /// <remarks/>
        Carat,

        /// <remarks/>
        Colon,

        /// <remarks/>
        Comma,

        /// <remarks/>
        Dollar,

        /// <remarks/>
        Equal,

        /// <remarks/>
        ExclamationMark,

        /// <remarks/>
        GreaterThan,

        /// <remarks/>
        LessThan,

        /// <remarks/>
        Hyphen,

        /// <remarks/>
        Percent,

        /// <remarks/>
        Pipe,

        /// <remarks/>
        Plus,

        /// <remarks/>
        Pound,

        /// <remarks/>
        SemiColin,

        /// <remarks/>
        Tilde,

        /// <remarks/>
        UnderScore,

        /// <remarks/>
        QuestionMark,

        /// <remarks/>
        Period,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class plugin
    {

        private command[] commandsField;

        private hotstring[] hotstringsField;

        private include[] includesField;

        private dataItem[] dataItemsField;

        private string versionField;

        private string minVersionField;

        private string profileNameField;

        private bool enabledField;

        private string nameField;

        private decimal schemaVersionField;

        public plugin()
        {
            this.minVersionField = "0.5.0";
            this.enabledField = true;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("command", IsNullable = false)]
        public command[] commands
        {
            get
            {
                return this.commandsField;
            }
            set
            {
                this.commandsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("hotstring", IsNullable = false)]
        public hotstring[] hotstrings
        {
            get
            {
                return this.hotstringsField;
            }
            set
            {
                this.hotstringsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("include", IsNullable = false)]
        public include[] includes
        {
            get
            {
                return this.includesField;
            }
            set
            {
                this.includesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("dataItem", IsNullable = false)]
        public dataItem[] dataItems
        {
            get
            {
                return this.dataItemsField;
            }
            set
            {
                this.dataItemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("0.5.0")]
        public string minVersion
        {
            get
            {
                return this.minVersionField;
            }
            set
            {
                this.minVersionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string profileName
        {
            get
            {
                return this.profileNameField;
            }
            set
            {
                this.profileNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool enabled
        {
            get
            {
                return this.enabledField;
            }
            set
            {
                this.enabledField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal schemaVersion
        {
            get
            {
                return this.schemaVersionField;
            }
            set
            {
                this.schemaVersionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class command
    {

        private string nameField;

        private string descriptionField;

        private string categoryField;

        private string labelField;

        private string snippitField;

        private commandType typeField;

        private string codeField;

        private string hotkeyField;

        private bool enabledField;

        public command()
        {
            this.categoryField = "None";
            this.typeField = commandType.include;
            this.enabledField = true;
        }

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "NCName")]
        public string category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "NCName")]
        public string label
        {
            get
            {
                return this.labelField;
            }
            set
            {
                this.labelField = value;
            }
        }

        /// <remarks/>
        public string snippit
        {
            get
            {
                return this.snippitField;
            }
            set
            {
                this.snippitField = value;
            }
        }

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(commandType.include)]
        public commandType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string hotkey
        {
            get
            {
                return this.hotkeyField;
            }
            set
            {
                this.hotkeyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool enabled
        {
            get
            {
                return this.enabledField;
            }
            set
            {
                this.enabledField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    public enum commandType
    {

        /// <remarks/>
        unknown,

        /// <remarks/>
        include,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class hotstring
    {

        private string nameField;

        private string descriptionField;

        private string categoryField;

        private bool forceclearField;

        private string snippitField;

        private bool tabifyField;

        private bool tabifyFieldSpecified;

        private string sendkeysField;

        private hotstringType typeField;

        private string codeField;

        private object[] replacementsField;

        private HotStringOptionsEnum[] hotStringOptionsField;

        private string triggerField;

        private bool enabledField;

        public hotstring()
        {
            this.categoryField = "None";
            this.forceclearField = false;
            this.tabifyField = false;
            this.typeField = hotstringType.Paste;
            this.enabledField = true;
        }

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "NCName")]
        public string category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }

        /// <remarks/>
        public bool forceclear
        {
            get
            {
                return this.forceclearField;
            }
            set
            {
                this.forceclearField = value;
            }
        }

        /// <remarks/>
        public string snippit
        {
            get
            {
                return this.snippitField;
            }
            set
            {
                this.snippitField = value;
            }
        }

        /// <remarks/>
        public bool tabify
        {
            get
            {
                return this.tabifyField;
            }
            set
            {
                this.tabifyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tabifySpecified
        {
            get
            {
                return this.tabifyFieldSpecified;
            }
            set
            {
                this.tabifyFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string sendkeys
        {
            get
            {
                return this.sendkeysField;
            }
            set
            {
                this.sendkeysField = value;
            }
        }

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(hotstringType.Paste)]
        public hotstringType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("inputFixedList", typeof(inputFixedList), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("inputReplacement", typeof(inputReplacement), IsNullable = false)]
        public object[] replacements
        {
            get
            {
                return this.replacementsField;
            }
            set
            {
                this.replacementsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("hotStringOption", IsNullable = false)]
        public HotStringOptionsEnum[] hotStringOptions
        {
            get
            {
                return this.hotStringOptionsField;
            }
            set
            {
                this.hotStringOptionsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string trigger
        {
            get
            {
                return this.triggerField;
            }
            set
            {
                this.triggerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool enabled
        {
            get
            {
                return this.enabledField;
            }
            set
            {
                this.enabledField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    public enum hotstringType
    {

        /// <remarks/>
        UnKnown,

        /// <remarks/>
        Paste,

        /// <remarks/>
        Inline,

        /// <remarks/>
        Code,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class inputFixedList
    {

        private string placeholderField;

        private string dialogtitleField;

        private string dialogtextField;

        private itemType[] listValuesField;

        /// <remarks/>
        public string placeholder
        {
            get
            {
                return this.placeholderField;
            }
            set
            {
                this.placeholderField = value;
            }
        }

        /// <remarks/>
        public string dialogtitle
        {
            get
            {
                return this.dialogtitleField;
            }
            set
            {
                this.dialogtitleField = value;
            }
        }

        /// <remarks/>
        public string dialogtext
        {
            get
            {
                return this.dialogtextField;
            }
            set
            {
                this.dialogtextField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("listItem", IsNullable = false)]
        public itemType[] listValues
        {
            get
            {
                return this.listValuesField;
            }
            set
            {
                this.listValuesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("listItem", Namespace = "", IsNullable = false)]
    public partial class itemType
    {

        private defaultType defaultField;

        private bool defaultFieldSpecified;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public defaultType @default
        {
            get
            {
                return this.defaultField;
            }
            set
            {
                this.defaultField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool defaultSpecified
        {
            get
            {
                return this.defaultFieldSpecified;
            }
            set
            {
                this.defaultFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    public enum defaultType
    {

        /// <remarks/>
        @true,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class inputReplacement
    {

        private string placeholderField;

        private string dialogtitleField;

        private string dialogtextField;

        private string dialoginitialvalueField;

        /// <remarks/>
        public string placeholder
        {
            get
            {
                return this.placeholderField;
            }
            set
            {
                this.placeholderField = value;
            }
        }

        /// <remarks/>
        public string dialogtitle
        {
            get
            {
                return this.dialogtitleField;
            }
            set
            {
                this.dialogtitleField = value;
            }
        }

        /// <remarks/>
        public string dialogtext
        {
            get
            {
                return this.dialogtextField;
            }
            set
            {
                this.dialogtextField = value;
            }
        }

        /// <remarks/>
        public string dialoginitialvalue
        {
            get
            {
                return this.dialoginitialvalueField;
            }
            set
            {
                this.dialoginitialvalueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    public enum HotStringOptionsEnum
    {

        /// <remarks/>
        TriggerInside,

        /// <remarks/>
        AutomaticBackSpaceOff,

        /// <remarks/>
        CaseSensitive,

        /// <remarks/>
        NoConform,

        /// <remarks/>
        OmitEndChar,

        /// <remarks/>
        Send,

        /// <remarks/>
        SendRaw,

        /// <remarks/>
        SendInput,

        /// <remarks/>
        SendPlay,

        /// <remarks/>
        SendEvent,

        /// <remarks/>
        ResetRecognizer,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class include
    {

        private string nameField;

        private string descriptionField;

        private string snippitField;

        private string codeField;

        private includeHotstring[] hotstringsField;

        private includeCommand[] commandsField;

        private bool enabledField;

        public include()
        {
            this.enabledField = true;
        }

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public string snippit
        {
            get
            {
                return this.snippitField;
            }
            set
            {
                this.snippitField = value;
            }
        }

        /// <remarks/>
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("hotstring", IsNullable = false)]
        public includeHotstring[] hotstrings
        {
            get
            {
                return this.hotstringsField;
            }
            set
            {
                this.hotstringsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("command", IsNullable = false)]
        public includeCommand[] commands
        {
            get
            {
                return this.commandsField;
            }
            set
            {
                this.commandsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool enabled
        {
            get
            {
                return this.enabledField;
            }
            set
            {
                this.enabledField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class includeHotstring
    {

        private string nameField;

        private string descriptionField;

        private string categoryField;

        private string triggerField;

        public includeHotstring()
        {
            this.categoryField = "None";
        }

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "NCName")]
        public string category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string trigger
        {
            get
            {
                return this.triggerField;
            }
            set
            {
                this.triggerField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class includeCommand
    {

        private string nameField;

        private string descriptionField;

        private string categoryField;

        private string hotkeyField;

        public includeCommand()
        {
            this.categoryField = "None";
        }

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "NCName")]
        public string category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string hotkey
        {
            get
            {
                return this.hotkeyField;
            }
            set
            {
                this.hotkeyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class dataItem
    {

        private string nameField;

        private string dataFileNameField;

        private string dataValueField;

        private bool overwriteField;

        private bool encodedField;

        public dataItem()
        {
            this.overwriteField = false;
            this.encodedField = false;
        }

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string dataFileName
        {
            get
            {
                return this.dataFileNameField;
            }
            set
            {
                this.dataFileNameField = value;
            }
        }

        /// <remarks/>
        public string dataValue
        {
            get
            {
                return this.dataValueField;
            }
            set
            {
                this.dataValueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool overwrite
        {
            get
            {
                return this.overwriteField;
            }
            set
            {
                this.overwriteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool encoded
        {
            get
            {
                return this.encodedField;
            }
            set
            {
                this.encodedField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class commands
    {

        private command[] commandField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("command")]
        public command[] command
        {
            get
            {
                return this.commandField;
            }
            set
            {
                this.commandField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class hotstrings
    {

        private hotstring[] hotstringField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("hotstring")]
        public hotstring[] hotstring
        {
            get
            {
                return this.hotstringField;
            }
            set
            {
                this.hotstringField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class dataItems
    {

        private dataItem[] dataItemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dataItem")]
        public dataItem[] dataItem
        {
            get
            {
                return this.dataItemField;
            }
            set
            {
                this.dataItemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class includes
    {

        private include[] includeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("include")]
        public include[] include
        {
            get
            {
                return this.includeField;
            }
            set
            {
                this.includeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class replacements
    {

        private object[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("inputFixedList", typeof(inputFixedList))]
        [System.Xml.Serialization.XmlElementAttribute("inputReplacement", typeof(inputReplacement))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class listValues
    {

        private itemType[] listItemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listItem")]
        public itemType[] listItem
        {
            get
            {
                return this.listItemField;
            }
            set
            {
                this.listItemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class SnippitInstal
    {

        private profile profileField;

        private plugin[] pluginField;

        private string codeVersionField;

        private decimal schemaVersionField;

        public SnippitInstal()
        {
            this.codeVersionField = "1.0.0.0";
        }

        /// <remarks/>
        public profile profile
        {
            get
            {
                return this.profileField;
            }
            set
            {
                this.profileField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("plugin")]
        public plugin[] plugin
        {
            get
            {
                return this.pluginField;
            }
            set
            {
                this.pluginField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("1.0.0.0")]
        public string codeVersion
        {
            get
            {
                return this.codeVersionField;
            }
            set
            {
                this.codeVersionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal schemaVersion
        {
            get
            {
                return this.schemaVersionField;
            }
            set
            {
                this.schemaVersionField = value;
            }
        }
    }
}