//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigByteTechnologies.Windows.Library.AHKSnipit.AHKSnipitLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BigByteTechnologies.Windows.Library.AHKSnipit.AHKSnipitLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate {0}.
        /// </summary>
        internal static string ErrorDuplicateKey {
            get {
                return ResourceManager.GetString("ErrorDuplicateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicates keys are not allowed.
        /// </summary>
        internal static string ErrorDuplicateKeysNotAllowed {
            get {
                return ResourceManager.GetString("ErrorDuplicateKeysNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicates are not allowed.
        /// </summary>
        internal static string ErrorDuplicateNotAllowed {
            get {
                return ResourceManager.GetString("ErrorDuplicateNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML does not contain any data..
        /// </summary>
        internal static string ErrorEmptyXmlString {
            get {
                return ResourceManager.GetString("ErrorEmptyXmlString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist.
        /// </summary>
        internal static string ErrorFileNotExist {
            get {
                return ResourceManager.GetString("ErrorFileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified file can not be found..
        /// </summary>
        internal static string ErrorFileNotFound {
            get {
                return ResourceManager.GetString("ErrorFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid format.
        /// </summary>
        internal static string ErrorInvalidFormat {
            get {
                return ResourceManager.GetString("ErrorInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one item can be marked as default.
        /// </summary>
        internal static string ErrorItemTypeDefault {
            get {
                return ResourceManager.GetString("ErrorItemTypeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Xml! schemaVersion attribute not found..
        /// </summary>
        internal static string ErrorMissingSchemaVersion {
            get {
                return ResourceManager.GetString("ErrorMissingSchemaVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin Parent property is null.
        /// </summary>
        internal static string ErrorPluginParentNull {
            get {
                return ResourceManager.GetString("ErrorPluginParentNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create instance of Profile from xml file.
        /// </summary>
        internal static string ErrorPluginsConstructorProfileRead {
            get {
                return ResourceManager.GetString("ErrorPluginsConstructorProfileRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Profile Minimum version is newer than the current version..
        /// </summary>
        internal static string ErrorProfileMinVersionNewer {
            get {
                return ResourceManager.GetString("ErrorProfileMinVersionNewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml is outside the valid range for attribute schemaVersion. Valid range is from &apos;{0|&apos; to &apos;{1}&apos;.
        /// </summary>
        internal static string ErrorSchemVersion {
            get {
                return ResourceManager.GetString("ErrorSchemVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be empty.
        /// </summary>
        internal static string ErrorValueMutNotBeNull {
            get {
                return ResourceManager.GetString("ErrorValueMutNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key is missing from xml data. Maps must have valid keys.
        /// </summary>
        internal static string ErrorXmlMapKeyMissing {
            get {
                return ResourceManager.GetString("ErrorXmlMapKeyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Letters, Number and Underscore are accepted.
        /// </summary>
        internal static string ErrroNumberLettersUnserscore {
            get {
                return ResourceManager.GetString("ErrroNumberLettersUnserscore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; This is an auto-generated file. Do not change contents of this file!.
        /// </summary>
        internal static string FileAutoGenMessage {
            get {
                return ResourceManager.GetString("FileAutoGenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;{License
        ////* Copyright (C) 2014-2017  Paul Moss
        /// * 
        /// * This file is part of AhkSnippy.
        /// *
        /// * AhkSnippy is free software: you can redistribute it and/or modify
        /// * it under the terms of the GNU General Public License as published by
        /// * the Free Software Foundation, either version 3 of the License, or
        /// * (at your option) any later version.
        /// * 
        /// * AhkSnippy is distributed in the hope that it will be useful,
        /// * but WITHOUT ANY WARRANTY; without even the implied warranty of
        /// * MERCHANTABILITY or FITNE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FileLicenseHeaderText {
            get {
                return ResourceManager.GetString("FileLicenseHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Hotkey Combination is Invalid.
        /// </summary>
        internal static string HotKeyFormatInvalidExceptionInvalidCombination {
            get {
                return ResourceManager.GetString("HotKeyFormatInvalidExceptionInvalidCombination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Hotkey is missing trigger Key(s)..
        /// </summary>
        internal static string HotKeyFormatInvalidExceptionMissingTriggerKey {
            get {
                return ResourceManager.GetString("HotKeyFormatInvalidExceptionMissingTriggerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Combination was attempted but was missing a key on one side of the Combination..
        /// </summary>
        internal static string HotkeysCombineExceptionToFiewKeys {
            get {
                return ResourceManager.GetString("HotkeysCombineExceptionToFiewKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are too many keys to combine. Maximum of Two keys are supported..
        /// </summary>
        internal static string HotkeysCombineExceptionTooManyKeys {
            get {
                return ResourceManager.GetString("HotkeysCombineExceptionTooManyKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not valid xml..
        /// </summary>
        internal static string InvalidXml {
            get {
                return ResourceManager.GetString("InvalidXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt.
        /// </summary>
        internal static string KeyAlt {
            get {
                return ResourceManager.GetString("KeyAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl.
        /// </summary>
        internal static string KeyCtrl {
            get {
                return ResourceManager.GetString("KeyCtrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string KeyLeft {
            get {
                return ResourceManager.GetString("KeyLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string KeyNotSupportedExceptionDefault {
            get {
                return ResourceManager.GetString("KeyNotSupportedExceptionDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string KeyRight {
            get {
                return ResourceManager.GetString("KeyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;.
        /// </summary>
        internal static string KeysCombine {
            get {
                return ResourceManager.GetString("KeysCombine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        internal static string KeyShift {
            get {
                return ResourceManager.GetString("KeyShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hook.
        /// </summary>
        internal static string KeysHook {
            get {
                return ResourceManager.GetString("KeysHook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        internal static string KeysNativeBlock {
            get {
                return ResourceManager.GetString("KeysNativeBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any.
        /// </summary>
        internal static string KeysWildcard {
            get {
                return ResourceManager.GetString("KeysWildcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UP.
        /// </summary>
        internal static string KeyUP {
            get {
                return ResourceManager.GetString("KeyUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win.
        /// </summary>
        internal static string KeyWin {
            get {
                return ResourceManager.GetString("KeyWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog Input.
        /// </summary>
        internal static string ReplacementNameDialogInput {
            get {
                return ResourceManager.GetString("ReplacementNameDialogInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog List.
        /// </summary>
        internal static string ReplacementNameDialogList {
            get {
                return ResourceManager.GetString("ReplacementNameDialogList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be set.
        /// </summary>
        internal static string ValueHasToBeSet {
            get {
                return ResourceManager.GetString("ValueHasToBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;&lt;AhkKeyMap&gt;&lt;AhkMapValue&gt;&lt;Key&gt;Zero&lt;/Key&gt;&lt;AutoHotKeyValue&gt;0&lt;/AutoHotKeyValue&gt;&lt;DisplayValue&gt;0&lt;/DisplayValue&gt;&lt;Sort&gt;1&lt;/Sort&gt;&lt;/AhkMapValue&gt;&lt;AhkMapValue&gt;&lt;Key&gt;One&lt;/Key&gt;&lt;AutoHotKeyValue&gt;1&lt;/AutoHotKeyValue&gt;&lt;DisplayValue&gt;1&lt;/DisplayValue&gt;&lt;Sort&gt;2&lt;/Sort&gt;&lt;/AhkMapValue&gt;&lt;AhkMapValue&gt;&lt;Key&gt;Two&lt;/Key&gt;&lt;AutoHotKeyValue&gt;2&lt;/AutoHotKeyValue&gt;&lt;DisplayValue&gt;2&lt;/DisplayValue&gt;&lt;Sort&gt;3&lt;/Sort&gt;&lt;/AhkMapValue&gt;&lt;AhkMapValue&gt;&lt;Key&gt;Three&lt;/Key&gt;&lt;AutoHotKeyValue&gt;3&lt;/AutoHotKeyValue&gt;&lt;DisplayValue&gt;3&lt;/DisplayValue&gt;&lt;Sor [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XmlMapEndCharKeys {
            get {
                return ResourceManager.GetString("XmlMapEndCharKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;&lt;SortedMap&gt;&lt;Item&gt;&lt;Key&gt;UnKnown&lt;/Key&gt;&lt;Value&gt;Unknown Value&lt;/Value&gt;&lt;SortOrder&gt;0&lt;/SortOrder&gt;&lt;/Item&gt;&lt;Item&gt;&lt;Key&gt;Code&lt;/Key&gt;&lt;Value&gt;Code&lt;/Value&gt;&lt;SortOrder&gt;3&lt;/SortOrder&gt;&lt;/Item&gt;&lt;Item&gt;&lt;Key&gt;Inline&lt;/Key&gt;&lt;Value&gt;In-Line&lt;/Value&gt;&lt;SortOrder&gt;1&lt;/SortOrder&gt;&lt;/Item&gt;&lt;Item&gt;&lt;Key&gt;Paste&lt;/Key&gt;&lt;Value&gt;Paste&lt;/Value&gt;&lt;SortOrder&gt;2&lt;/SortOrder&gt;&lt;/Item&gt;&lt;/SortedMap&gt;.
        /// </summary>
        internal static string XmlMapHotStringType {
            get {
                return ResourceManager.GetString("XmlMapHotStringType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;&lt;AhkKeyMap&gt;&lt;AhkMapValue&gt;&lt;Key&gt;None&lt;/Key&gt;&lt;AutoHotKeyValue&gt;&lt;/AutoHotKeyValue&gt;&lt;DisplayValue&gt;None&lt;/DisplayValue&gt;&lt;Sort&gt;0&lt;/Sort&gt;&lt;/AhkMapValue&gt;&lt;AhkMapValue&gt;&lt;Key&gt;Send&lt;/Key&gt;&lt;AutoHotKeyValue&gt;&lt;/AutoHotKeyValue&gt;&lt;DisplayValue&gt;Send (default)&lt;/DisplayValue&gt;&lt;Sort&gt;1&lt;/Sort&gt;&lt;/AhkMapValue&gt;&lt;AhkMapValue&gt;&lt;Key&gt;SendInput&lt;/Key&gt;&lt;AutoHotKeyValue&gt;si&lt;/AutoHotKeyValue&gt;&lt;DisplayValue&gt;Send Input&lt;/DisplayValue&gt;&lt;Sort&gt;2&lt;/Sort&gt;&lt;/AhkMapValue&gt;&lt;AhkMapValue&gt;&lt;Key&gt;SendPlay&lt;/Key&gt;&lt;AutoHotKeyValue&gt;sp&lt;/AutoHotKeyValue [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XmlMapSendTypeEnum {
            get {
                return ResourceManager.GetString("XmlMapSendTypeEnum", resourceCulture);
            }
        }
    }
}
