//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigByteTechnologies.Windows.Library.AHKSnipit.AHKSnipitLib.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AutoHotkey Snippit")]
        public string DataFolder {
            get {
                return ((string)(this["DataFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Xml")]
        public string XmlFolder {
            get {
                return ((string)(this["XmlFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Profiles")]
        public string ProfilesFolder {
            get {
                return ((string)(this["ProfilesFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Snips")]
        public string SnipsFolder {
            get {
                return ((string)(this["SnipsFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Plugins")]
        public string PluginsFolder {
            get {
                return ((string)(this["PluginsFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("settings.ini")]
        public string SettingsIni {
            get {
                return ((string)(this["SettingsIni"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("app.ini")]
        public string AppIni {
            get {
                return ((string)(this["AppIni"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5.0.0")]
        public string DefaultMinVersionString {
            get {
                return ((string)(this["DefaultMinVersionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PROFILE")]
        public string IniProfileSection {
            get {
                return ((string)(this["IniProfileSection"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("current")]
        public string IniProfileCurrent {
            get {
                return ((string)(this["IniProfileCurrent"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SCRIPT")]
        public string IniScriptSection {
            get {
                return ((string)(this["IniScriptSection"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("path")]
        public string IniScriptPath {
            get {
                return ((string)(this["IniScriptPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("version")]
        public string IniScriptVersion {
            get {
                return ((string)(this["IniScriptVersion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("load_state")]
        public string IniScriptLoadState {
            get {
                return ((string)(this["IniScriptLoadState"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^([0-9]+)(\\.[0-9]+)?(\\.[0-9]+)?(\\.[0-9]+)?$")]
        public string RegexVersion {
            get {
                return ((string)(this["RegexVersion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^[a-zA-Z0-9_]+$")]
        public string RegexLetterNumberUnderscore {
            get {
                return ((string)(this["RegexLetterNumberUnderscore"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^[~<>!#$+^*]*[a-z0-9]+(\\sup)?$|^[~<>!#$+^*]*[a-z0-9]+\\s*&\\s*[a-z0-9]+$")]
        public string RegexHotstring {
            get {
                return ((string)(this["RegexHotstring"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".snippit")]
        public string DefaultSnippitExt {
            get {
                return ((string)(this["DefaultSnippitExt"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Inline")]
        public string SnipsFolderInline {
            get {
                return ((string)(this["SnipsFolderInline"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WRITER")]
        public string IniWriterSection {
            get {
                return ((string)(this["IniWriterSection"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("exitcode")]
        public string IniWriterExitCode {
            get {
                return ((string)(this["IniWriterExitCode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("inc")]
        public string PluginIncludeSubFolder {
            get {
                return ((string)(this["PluginIncludeSubFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cmd")]
        public string PluginCmdSubFolder {
            get {
                return ((string)(this["PluginCmdSubFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""UTF-8""?><xs:schema xmlns:xs=""http://www.w3.org/2001/XMLSchema"" elementFormDefault=""qualified""><xs:element name=""map""><xs:complexType><xs:sequence><xs:element maxOccurs=""unbounded"" name=""item""><xs:complexType><xs:sequence><xs:element name=""key"" type=""xs:string""/><xs:element name=""value"" type=""xs:string""/></xs:sequence></xs:complexType></xs:element></xs:sequence></xs:complexType></xs:element></xs:schema>
")]
        public string XsdMap {
            get {
                return ((string)(this["XsdMap"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""UTF-8""?><map><item><key>TriggerInside</key><value>?</value></item><item><key>AutomaticBackSpaceOff</key><value>b0</value></item><item><key>CaseSensitive</key><value>c</value></item><item><key>NoConform</key><value>c1</value></item><item><key>OmitEndChar</key><value>o</value></item><item><key>SendRaw</key><value>r</value></item><item><key>SendInput</key><value>SI</value></item><item><key>SendPlay</key><value>SP</value></item><item><key>SendEvent</key><value>SE</value></item><item><key>ResetRecognizer</key><value>z</value></item></map>
")]
        public string XmlMapHotstringOpt {
            get {
                return ((string)(this["XmlMapHotstringOpt"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("path")]
        public string IniWriterScriptPath {
            get {
                return ((string)(this["IniWriterScriptPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LaunchPath")]
        public string IniLaunchPath {
            get {
                return ((string)(this["IniLaunchPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("APPS")]
        public string IniSettingsAppSection {
            get {
                return ((string)(this["IniSettingsAppSection"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("windowspy")]
        public string IniSettingsAppWindowSpy {
            get {
                return ((string)(this["IniSettingsAppWindowSpy"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://tiny.cc/snipdonate/")]
        public string UrlDonate {
            get {
                return ((string)(this["UrlDonate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"UTF-8\"?><map><item><key>A</key><value>a</value></it" +
            "em><item><key>B</key><value>b</value></item><item><key>C</key><value>c</value></" +
            "item><item><key>D</key><value>d</value></item><item><key>E</key><value>e</value>" +
            "</item><item><key>F</key><value>f</value></item><item><key>G</key><value>g</valu" +
            "e></item><item><key>H</key><value>h</value></item><item><key>I</key><value>i</va" +
            "lue></item><item><key>J</key><value>j</value></item><item><key>K</key><value>k</" +
            "value></item><item><key>L</key><value>l</value></item><item><key>M</key><value>m" +
            "</value></item><item><key>N</key><value>n</value></item><item><key>O</key><value" +
            ">o</value></item><item><key>P</key><value>p</value></item><item><key>Q</key><val" +
            "ue>q</value></item><item><key>R</key><value>r</value></item><item><key>S</key><v" +
            "alue>s</value></item><item><key>T</key><value>t</value></item><item><key>U</key>" +
            "<value>u</value></item><item><key>V</key><value>v</value></item><item><key>W</ke" +
            "y><value>w</value></item><item><key>X</key><value>x</value></item><item><key>Y</" +
            "key><value>y</value></item><item><key>Z</key><value>z</value></item><item><key>N" +
            "umpad0</key><value>0</value></item><item><key>Numpad1</key><value>1</value></ite" +
            "m><item><key>Numpad2</key><value>2</value></item><item><key>Numpad3</key><value>" +
            "3</value></item><item><key>Numpad4</key><value>4</value></item><item><key>Numpad" +
            "5</key><value>5</value></item><item><key>Numpad6</key><value>6</value></item><it" +
            "em><key>Numpad7</key><value>7</value></item><item><key>Numpad8</key><value>8</va" +
            "lue></item><item><key>Numpad9</key><value>9</value></item><item><key>Space</key>" +
            "<value>&#x20;</value></item><item><key>Tab</key><value>&#x9;</value></item></map" +
            ">")]
        public string XmlMapKey2 {
            get {
                return ((string)(this["XmlMapKey2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data")]
        public string DataItemsFolder {
            get {
                return ((string)(this["DataItemsFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.1")]
        public decimal MinAllowedSchemaVersion {
            get {
                return ((decimal)(this["MinAllowedSchemaVersion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.1")]
        public decimal MaxAllowedSchemaVersion {
            get {
                return ((decimal)(this["MaxAllowedSchemaVersion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://github.com/Amourspirit/Mini-Framework")]
        public string UrlProjectHome {
            get {
                return ((string)(this["UrlProjectHome"]));
            }
        }
    }
}
